name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Extract docker tag
        id: extract_tag
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
        run: |
          docker compose -f docker-compose.build.yml build
          docker compose -f docker-compose.build.yml push
        

